refactor: dont use miranum-consulting as root
FlowSquad/miranum-consulting pull request #15
Opened 2023-05-04 09:19 UTC by DaAnda97

**Issue**
Closes #13 

**Description**
Having miranum-consulting as parent restricts us having naming two modules the same way in two different showcase projects.

**Checklist**
* [ ] Code is easy to understand
* [ ] No obvious errors or bugs
* [ ] CI/CD Pipelines did run successfully
* [ ] Tests were implemented
* [ ] Documentation was created

2023-05-08 06:07 UTC, rami-nk requested changes
Seems to be fine! You now can rename the projects that you had to rename because of the root being the parent of all other submodules in order to avoid naming clashes.

2023-05-08 10:07 UTC, DaAnda97 commented
That's still impossible due to the root pom. Would it make sense to restructure our consulting repo into a mono repo?

2023-05-08 11:31 UTC, rami-nk commented
> That's still impossible due to the root pom. Would it make sense to restructure our consulting repo into a mono repo?

Oh ok gotcha. I mean this was at least my intention behind this task, so I guess we should do that to not have to invent new names every time creating new project submods. What do you think?

2023-05-10 08:16 UTC, DaAnda97 commented
Yea. Could you create a new issue for that and approve this one? I did some pom refactoring and replaced the miranum  snapshot versions with the versions in central

2023-05-10 09:20 UTC, rami-nk approved these changes

2023-05-10 09:22 UTC, merged